<?php
header('Content-Type: text/html; charset=utf-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>WW2FPS AI Lab · What We Learned</title>
<style>
:root{color-scheme:dark;--bg:#0d110c;--panel:#171d14;--panel2:#11160f;--line:#303a29;--text:#eef0df;--muted:#a9b098;--good:#92b879;--warn:#d6b86d;--us:#7fa6d8;--ge:#d7bd72}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#1c2418 0,#0d110c 38%,#090c08 100%);color:var(--text);font:14px/1.45 Arial,sans-serif}.wrap{max-width:1280px;margin:0 auto;padding:22px}.top{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.eyebrow{font-size:11px;letter-spacing:.14em;color:#8e987d;text-transform:uppercase}.top h1{margin:3px 0 4px;font-size:27px}.sub{color:var(--muted);max-width:780px}.actions{display:flex;gap:8px;flex-wrap:wrap}.btn{display:inline-block;padding:8px 11px;border:1px solid #46513c;border-radius:7px;background:#1c2518;color:#eef0df;text-decoration:none;cursor:pointer;font-size:12px}.btn:hover{background:#273320}.cards{display:grid;grid-template-columns:repeat(6,minmax(130px,1fr));gap:10px;margin-bottom:12px}.card,.panel{background:rgba(23,29,20,.94);border:1px solid var(--line);border-radius:10px;box-shadow:0 8px 26px rgba(0,0,0,.18)}.card{padding:13px}.card .k{font-size:10px;text-transform:uppercase;letter-spacing:.09em;color:#8f9980}.card .v{font-size:22px;font-weight:700;margin-top:3px}.card .d{font-size:10px;color:var(--muted);margin-top:2px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.panel{padding:15px;min-width:0}.panel.wide{grid-column:1/-1}.panel h2{font-size:14px;margin:0 0 3px}.panel .hint{font-size:11px;color:var(--muted);margin-bottom:10px}.chart{width:100%;height:260px;display:block;background:var(--panel2);border:1px solid #293123;border-radius:7px}.learned{display:grid;grid-template-columns:1.25fr .75fr;gap:12px}.insights{margin:8px 0 0;padding-left:20px}.insights li{margin:8px 0}.pill{display:inline-block;border:1px solid #3b4732;background:#20291b;border-radius:999px;padding:3px 7px;font-size:10px;color:#c8d0b9;margin:2px 3px 2px 0}.tableWrap{overflow:auto;max-height:350px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{padding:7px 8px;border-bottom:1px solid #293123;text-align:left;white-space:nowrap}th{position:sticky;top:0;background:#171d14;color:#9fa790}.delta.up{color:#9fc88a}.delta.down{color:#d3947f}.empty{color:var(--muted);padding:18px 0}.status{font-size:11px;color:var(--muted);margin-top:8px}.error{color:#df9898}@media(max-width:980px){.cards{grid-template-columns:repeat(3,1fr)}.grid,.learned{grid-template-columns:1fr}.panel.wide{grid-column:auto}}@media(max-width:560px){.wrap{padding:12px}.top{display:block}.actions{margin-top:10px}.cards{grid-template-columns:repeat(2,1fr)}.card .v{font-size:18px}.chart{height:220px}}
</style>
</head>
<body><div class="wrap">
<div class="top"><div><div class="eyebrow">WW2FPS AI Laboratory · Genome v2</div><h1>What We Learned</h1><div class="sub">Training performance, policy evolution, procedural-scenario generalization and the scenario memories the commander can reuse on future maps.</div></div><div class="actions"><a class="btn" href="/grasstex/battle_sim.php">← Battle Lab</a><button class="btn" id="refresh">Refresh</button></div></div>
<div class="cards" id="cards"><div class="card"><div class="k">Genome revision</div><div class="v" id="rev">—</div><div class="d" id="trained">loading</div></div><div class="card"><div class="k">Last fitness</div><div class="v" id="fitness">—</div><div class="d">selection score</div></div><div class="card"><div class="k">Training matches</div><div class="v" id="matches">—</div><div class="d">review window</div></div><div class="card"><div class="k">Scenario memories</div><div class="v" id="memories">—</div><div class="d">reusable experiences</div></div><div class="card"><div class="k">Latest generalization</div><div class="v" id="generalization">—</div><div class="d">mean minus map variance</div></div><div class="card"><div class="k">Rules</div><div class="v" id="rules">—</div><div class="d">current doctrine genome</div></div></div>
<div class="learned"><section class="panel"><h2>What the AI learned</h2><div class="hint">Deterministic interpretation of the latest promoted genome and training results.</div><ul class="insights" id="insights"><li>Loading training history…</li></ul></section><section class="panel"><h2>Current doctrine</h2><div class="hint">Force-allocation genes currently active.</div><div id="doctrine"></div></section></div>
<div class="grid" style="margin-top:12px">
<section class="panel"><h2>Policy fitness by revision</h2><div class="hint">Promoted genome score over time.</div><canvas class="chart" id="historyChart"></canvas></section>
<section class="panel"><h2>Latest generation candidates</h2><div class="hint">Selection fitness / average tactical score from the newest training seed.</div><canvas class="chart" id="candidateChart"></canvas></section>
<section class="panel"><h2>Scenario generalization</h2><div class="hint">Average candidate score by procedural scenario seed. Large spread indicates overfitting.</div><canvas class="chart" id="scenarioChart"></canvas></section>
<section class="panel"><h2>Win distribution</h2><div class="hint">Candidate-side results from the retained training matches.</div><canvas class="chart" id="winChart"></canvas></section>
<section class="panel wide"><h2>Genome changes</h2><div class="hint">Current promoted genome compared with the previous promoted revision.</div><div class="tableWrap"><table><thead><tr><th>Gene</th><th>Previous</th><th>Current</th><th>Change</th></tr></thead><tbody id="geneRows"></tbody></table></div></section>
<section class="panel"><h2>Tactical rule evolution</h2><div class="hint">Rules added or removed at the last promotion.</div><div id="ruleChanges"></div></section>
<section class="panel"><h2>Scenario recall</h2><div class="hint">Most recent map analogies actually used by the commander.</div><div id="recall"></div></section>
<section class="panel wide"><h2>Best remembered scenarios</h2><div class="hint">High-performing experiences available to seed doctrine on similar future maps.</div><div class="tableWrap"><table><thead><tr><th>Seed</th><th>Scenario</th><th>Score</th><th>Revision</th><th>Candidate</th><th>Stored</th></tr></thead><tbody id="memoryRows"></tbody></table></div><div class="status" id="status"></div></section>
</div></div>
<script>
(function(){
'use strict';var API='/grasstex/battle_learning.php?view=dashboard&days=14&ts=';
function el(id){return document.getElementById(id)}function num(v,d){return Number.isFinite(+v)?(+v).toFixed(d==null?1:d):'—'}function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]});}function short(s,n){s=String(s||'');return s.length>(n||22)?s.slice(0,(n||22)-1)+'…':s;}function fmtDate(s){if(!s)return'—';try{return new Date(s).toLocaleString();}catch(_){return s;}}
function fitCanvas(c){var r=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);c.width=Math.max(1,Math.floor(r.width*d));c.height=Math.max(1,Math.floor(r.height*d));var x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);return{x:x,w:r.width,h:r.height};}
function axes(ctx,w,h,min,max){ctx.strokeStyle='#34402d';ctx.lineWidth=1;for(var i=0;i<=4;i++){var y=16+(h-42)*i/4;ctx.beginPath();ctx.moveTo(38,y);ctx.lineTo(w-10,y);ctx.stroke();ctx.fillStyle='#87917b';ctx.font='10px Arial';var v=max-(max-min)*i/4;ctx.fillText(num(v,0),3,y+3);}ctx.strokeStyle='#59634f';ctx.beginPath();ctx.moveTo(38,16);ctx.lineTo(38,h-26);ctx.lineTo(w-10,h-26);ctx.stroke();}
function barChart(c,items,valueKey,labelKey){var o=fitCanvas(c),ctx=o.x,w=o.w,h=o.h;ctx.clearRect(0,0,w,h);if(!items.length){ctx.fillStyle='#89927d';ctx.fillText('No training data yet',16,25);return;}var vals=items.map(function(x){return+x[valueKey]||0;}),min=Math.min(0,Math.min.apply(null,vals)),max=Math.max(1,Math.max.apply(null,vals));axes(ctx,w,h,min,max);var plotW=w-55,bw=Math.max(8,plotW/items.length*.62),gap=plotW/items.length;items.forEach(function(it,i){var v=+it[valueKey]||0,x=43+i*gap+(gap-bw)/2,zero=16+(h-42)*(max/(max-min||1)),y=16+(h-42)*((max-v)/(max-min||1));ctx.fillStyle=v>=0?'#8eaa78':'#b27e6e';ctx.fillRect(x,Math.min(y,zero),bw,Math.max(1,Math.abs(zero-y)));ctx.save();ctx.translate(x+bw/2,h-21);ctx.rotate(-.28);ctx.textAlign='right';ctx.fillStyle='#aab19e';ctx.font='9px Arial';ctx.fillText(short(it[labelKey],16),0,0);ctx.restore();});}
function lineChart(c,items){var o=fitCanvas(c),ctx=o.x,w=o.w,h=o.h;ctx.clearRect(0,0,w,h);if(!items.length){ctx.fillStyle='#89927d';ctx.fillText('No promotions yet',16,25);return;}var vals=items.map(function(x){return+x.score||0;}),min=Math.min(0,Math.min.apply(null,vals)),max=Math.max(1,Math.max.apply(null,vals));axes(ctx,w,h,min,max);ctx.strokeStyle='#9dbc83';ctx.lineWidth=2;ctx.beginPath();items.forEach(function(it,i){var x=items.length===1?w/2:42+(w-58)*i/(items.length-1),y=16+(h-42)*(max-(+it.score||0))/(max-min||1);if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);ctx.fillStyle='#dce4d3';ctx.fillRect(x-2,y-2,4,4);ctx.fillStyle='#aab19e';ctx.font='9px Arial';ctx.fillText('r'+(it.revision||0),x-5,h-10);});ctx.stroke();}
function winChart(c,matches){var o=fitCanvas(c),ctx=o.x,w=o.w,h=o.h;ctx.clearRect(0,0,w,h);var wins=0,loss=0,draw=0;matches.forEach(function(m){if(m.winner===m.candidateFaction)wins++;else if(m.winner==='draw'||m.winner==='none')draw++;else loss++;});var total=wins+loss+draw;if(!total){ctx.fillStyle='#89927d';ctx.fillText('No match results yet',16,25);return;}var vals=[['candidate wins',wins,'#8faa78'],['baseline wins',loss,'#b47e6d'],['draw / none',draw,'#8a9183']],cx=w*.30,cy=h*.50,r=Math.min(w,h)*.28,start=-Math.PI/2;vals.forEach(function(a){var end=start+Math.PI*2*a[1]/total;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,start,end);ctx.closePath();ctx.fillStyle=a[2];ctx.fill();start=end;});ctx.beginPath();ctx.arc(cx,cy,r*.55,0,Math.PI*2);ctx.fillStyle='#11160f';ctx.fill();ctx.textAlign='center';ctx.fillStyle='#eef0df';ctx.font='700 18px Arial';ctx.fillText(total,cx,cy+6);ctx.textAlign='left';ctx.font='11px Arial';vals.forEach(function(a,i){var y=cy-32+i*32;ctx.fillStyle=a[2];ctx.fillRect(w*.58,y-8,11,11);ctx.fillStyle='#cbd1c0';ctx.fillText(a[0]+' · '+a[1],w*.58+18,y+1);});}
function ruleSig(r){return(r.action||'?')+' ← '+(r.when||[]).slice().sort().join(' + ')}
function describe(data){var out=[],sum=(data.trainingSummaries||[]).slice(-1)[0],hist=data.policyHistory||[],cur=data.policy&&data.policy.genome,prev=hist.length>1?hist[hist.length-2].genome:null;if(sum){var b=sum.best||{};out.push('Latest training seed '+(sum.trainingSeed||'—')+' evaluated '+(sum.totalMatches||0)+' matches across '+((sum.scenarioSeeds||[]).length||0)+' generated maps.');if(sum.promoted)out.push('The generation promoted a new genome. Its selection fitness was '+num(b.selectionFitness,2)+' with generalization '+num(b.generalization,2)+'; map-to-map standard deviation was '+num(b.scenarioStd,2)+'.');else out.push('No genome was promoted in the latest generation; the best candidate did not clear the promotion/generalization gate.');if(b.scenarioScores&&b.scenarioScores.length){var ordered=b.scenarioScores.slice().sort(function(a,c){return c.score-a.score;});out.push('Best map was '+short(ordered[0].seed,30)+' ('+num(ordered[0].score,1)+'); hardest was '+short(ordered[ordered.length-1].seed,30)+' ('+num(ordered[ordered.length-1].score,1)+').');}}
if(cur&&prev){var del=[];Object.keys(cur.doctrine||{}).forEach(function(k){if(typeof cur.doctrine[k]==='number'&&typeof prev.doctrine[k]==='number'){var d=cur.doctrine[k]-prev.doctrine[k];if(Math.abs(d)>.025)del.push(k+' '+(d>0?'increased':'decreased')+' by '+Math.abs(d).toFixed(2));}else if(cur.doctrine[k]!==prev.doctrine[k])del.push(k+' changed from '+prev.doctrine[k]+' to '+cur.doctrine[k]);});if(del.length)out.push('Doctrine shift: '+del.slice(0,4).join('; ')+'.');var A=new Set((prev.rules||[]).map(ruleSig)),B=new Set((cur.rules||[]).map(ruleSig)),added=[...B].filter(function(x){return!A.has(x)});if(added.length)out.push('New tactical idea'+(added.length>1?'s':'')+': '+added.slice(0,3).join('; ')+'.');}
var recall=(data.recalls||[]).slice(-1)[0];if(recall&&recall.sources&&recall.sources.length){var src=recall.sources.slice().sort(function(a,b){return b.similarity-a.similarity;});out.push('Latest scenario recall blended '+src.length+' prior experience'+(src.length===1?'':'s')+'. Strongest analogy was '+Math.round((src[0].similarity||0)*100)+'% similar to '+short(src[0].seed||src[0].scenarioId,28)+'.');}if(!out.length)out.push('Run a Genome v2 training generation to populate this review.');return out;}
function geneRows(cur,prev){var tbody=el('geneRows');tbody.innerHTML='';if(!cur){tbody.innerHTML='<tr><td colspan="4">No promoted Genome v2 yet.</td></tr>';return;}var rows=[];['doctrine','parameters'].forEach(function(section){Object.keys(cur[section]||{}).forEach(function(k){var v=cur[section][k],p=prev&&prev[section]?prev[section][k]:null,d=(typeof v==='number'&&typeof p==='number')?v-p:null;rows.push({k:section+'.'+k,p:p,v:v,d:d});});});rows.forEach(function(r){var tr=document.createElement('tr'),delta=r.d==null?(r.p==null?'new':(r.v===r.p?'—':'changed')):(Math.abs(r.d)<.0005?'—':((r.d>0?'+':'')+num(r.d,3)));tr.innerHTML='<td>'+esc(r.k)+'</td><td>'+esc(r.p==null?'—':r.p)+'</td><td>'+esc(r.v)+'</td><td class="delta '+(r.d>0?'up':r.d<0?'down':'')+'">'+esc(delta)+'</td>';tbody.appendChild(tr);});}
function render(data){var policy=data.policy||{},g=policy.genome||null,h=data.policyHistory||[],prev=h.length>1?h[h.length-2].genome:null;el('rev').textContent='r'+(policy.revision||0);el('trained').textContent=policy.trainedAt?fmtDate(policy.trainedAt):'no promoted v2 genome';el('fitness').textContent=num(policy.score,2);el('matches').textContent=(data.matches||[]).length;el('memories').textContent=data.memoryCount||0;var last=(data.trainingSummaries||[]).slice(-1)[0];el('generalization').textContent=last&&last.best?num(last.best.generalization,1):'—';el('rules').textContent=g&&g.rules?g.rules.length:'—';
var insights=describe(data);el('insights').innerHTML=insights.map(function(x){return'<li>'+esc(x)+'</li>';}).join('');var doc=g&&g.doctrine||{};el('doctrine').innerHTML=Object.keys(doc).map(function(k){return'<span class="pill">'+esc(k)+': <b>'+esc(typeof doc[k]==='number'?num(doc[k],2):doc[k])+'</b></span>';}).join('')||'<div class="empty">No Genome v2 doctrine promoted yet.</div>';
lineChart(el('historyChart'),h.filter(function(x){return x.score!=null;}));var latestSeed=last&&last.trainingSeed,latestMatches=(data.matches||[]).filter(function(m){return!latestSeed||m.trainingSeed===latestSeed;}),cand={};latestMatches.forEach(function(m){var id=m.candidateId||'?';(cand[id]=cand[id]||[]).push(+m.score||0);});var candItems=Object.keys(cand).map(function(k){return{label:k,value:mean(cand[k])};}).sort(function(a,b){return b.value-a.value;});barChart(el('candidateChart'),candItems,'value','label');var scenarios=(data.scenarioStats||[]).slice().sort(function(a,b){return b.avgScore-a.avgScore;});barChart(el('scenarioChart'),scenarios,'avgScore','seed');winChart(el('winChart'),latestMatches);geneRows(g,prev);
var curRules=new Set((g&&g.rules||[]).map(ruleSig)),prevRules=new Set((prev&&prev.rules||[]).map(ruleSig)),added=[...curRules].filter(function(x){return!prevRules.has(x)}),removed=[...prevRules].filter(function(x){return!curRules.has(x)});el('ruleChanges').innerHTML=(added.length?'<div><b>Added</b><br>'+added.map(function(x){return'<span class="pill">'+esc(x)+'</span>';}).join('')+'</div>':'')+(removed.length?'<div style="margin-top:8px"><b>Removed</b><br>'+removed.map(function(x){return'<span class="pill">'+esc(x)+'</span>';}).join('')+'</div>':'')+(!added.length&&!removed.length?'<div class="empty">No structural rule change in the latest promotion.</div>':'');
var rec=(data.recalls||[]).slice(-3).reverse();el('recall').innerHTML=rec.length?rec.map(function(r){var src=r.sources||[];return'<div style="margin-bottom:10px"><b>'+esc(short(r.seed||r.scenarioId,34))+'</b><br>'+(src.length?src.map(function(s){return'<span class="pill">'+Math.round((s.similarity||0)*100)+'% · '+esc(short(s.seed||s.scenarioId,22))+' · score '+num(s.score,1)+'</span>';}).join(''):'<span class="status">No close prior analogies.</span>')+'</div>';}).join(''):'<div class="empty">No scenario recall events yet.</div>';
var tbody=el('memoryRows');tbody.innerHTML='';(data.experiences||[]).slice(0,30).forEach(function(x){var tr=document.createElement('tr');tr.innerHTML='<td title="'+esc(x.seed)+'">'+esc(short(x.seed,28))+'</td><td>'+esc(x.scenarioId||'—')+'</td><td>'+num(x.score,2)+'</td><td>r'+(x.revision||0)+'</td><td>'+esc(x.candidateId||'—')+'</td><td>'+esc(fmtDate(x.storedAt))+'</td>';tbody.appendChild(tr);});if(!tbody.children.length)tbody.innerHTML='<tr><td colspan="6">No scenario memories stored yet.</td></tr>';el('status').textContent='Updated '+fmtDate(data.generatedAt)+' · review window '+data.days+' days';}
function mean(a){return a.length?a.reduce(function(x,y){return x+y;},0)/a.length:0}async function load(){el('status').textContent='Loading…';try{var r=await fetch(API+Date.now(),{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||('HTTP '+r.status));render(j);}catch(e){el('status').innerHTML='<span class="error">Review failed: '+esc(e.message||e)+'</span>';console.error(e);}}el('refresh').addEventListener('click',load);window.addEventListener('resize',function(){clearTimeout(window.__metricsResize);window.__metricsResize=setTimeout(load,120);});load();
})();
</script></body></html>
