/* Battle Sim / ww2fps AI lab v20 Genome v2 trainer.
   Four structurally different candidate genomes x three procedural scenarios x both factions =
   24 deterministic matches per generation. Every match is checkpointed to the server and its
   disposable scene resources are torn down before the next match begins. */
(function(root){
'use strict';if(!root.BattleAIPolicy||!root.BattleCommanderAI||!root.BattleScenarioGenerator||!root.BattleTownObjectives)return;
function telemetry(sim,type,data){if(root.BattleTelemetry)root.BattleTelemetry.record(type,data,sim);}function other(f){return f==='us'?'ge':'us';}
function yieldToBrowser(headless){return new Promise(function(resolve){var visible=!root.document||!root.document.hidden;if(!headless&&visible&&root.requestAnimationFrame){root.requestAnimationFrame(function(){resolve();});}else setTimeout(resolve,0);});}
function reportProgress(runOpts,detail){try{if(runOpts&&typeof runOpts.onProgress==='function')runOpts.onProgress(detail);}catch(_){}}
function units(sim,faction){var all=root.BattleModules?root.BattleModules.unitsFor(sim):((sim._roster&&sim._roster[faction])||[]);return all.filter(function(u){return u&&u.faction===faction&&!u.dead&&u.countsForElimination!==false;});}
function forceValue(sim,faction){var total=0;units(sim,faction).forEach(function(u){total+=u.scoreValue==null?1:+u.scoreValue;});return total;}function objectiveCounts(sim){var c=sim.objectiveControl||{};return c.counts||{us:c.us||0,ge:c.ge||0};}function fixedStep(sim,dt){sim._trainerStepActive=true;try{if(sim.step)sim.step(dt);else sim._frame(dt);}finally{sim._trainerStepActive=false;}}function mean(a){return a.length?a.reduce(function(x,y){return x+y;},0)/a.length:0;}function stdev(a){if(a.length<2)return 0;var m=mean(a);return Math.sqrt(mean(a.map(function(x){return(x-m)*(x-m);})));}
function sceneCounts(sim){var s=sim&&sim.scene;return s?{meshes:s.meshes?s.meshes.length:0,materials:s.materials?s.materials.length:0,transforms:s.transformNodes?s.transformNodes.length:0}:{};}
function disposeMatchResources(sim){
  if(!sim)return;sim.paused=true;
  ['us','ge'].forEach(function(f){var roster=sim._roster&&sim._roster[f]||[];for(var i=0;i<roster.length;i++){var u=roster[i];try{if(root.BattleNavigation)root.BattleNavigation.releaseWindow(u);}catch(_){}u._navCache=null;u.target=null;try{if(u.root&&!u.root.isDisposed())u.root.dispose();}catch(_){try{u.root&&u.root.dispose();}catch(__){}}}});
  sim._roster={us:[],ge:[]};sim._moduleUnits=[];sim.factions={us:{alive:0,kills:0,squads:[]},ge:{alive:0,kills:0,squads:[]}};sim.obstacles=[];sim.objectives=[];sim._objectives=[];sim.objectiveControl=null;sim.objectiveStats=null;sim.objectiveHold=null;sim._aiAccum=0;sim._commandAccum=0;
  try{root.BattleTownObjectives.releaseCurrent(sim.scene);}catch(e){console.warn('[TRAINING] scenario release failed',e);}
  try{var eng=sim.scene&&sim.scene.getEngine&&sim.scene.getEngine();if(eng&&eng.wipeCaches)eng.wipeCaches(true);}catch(_){}
}
async function settleAfterCleanup(){await new Promise(function(resolve){setTimeout(resolve,16);});await new Promise(function(resolve){setTimeout(resolve,0);});}
function scoreMatch(sim,candidateFaction){var enemy=other(candidateFaction),counts=objectiveCounts(sim),stats=sim.objectiveStats||{},caps=stats.capturesByFaction||{},pressure=stats.pressureSecondsByFaction||{},score=0;if(sim.winner===candidateFaction)score+=120;else if(sim.winner===enemy)score-=120;score+=((counts[candidateFaction]||0)-(counts[enemy]||0))*28;score+=(forceValue(sim,candidateFaction)-forceValue(sim,enemy))*1.25;score+=((caps[candidateFaction]||0)-(caps[enemy]||0))*16;score+=((pressure[candidateFaction]||0)-(pressure[enemy]||0))*.08;if(sim.winner===candidateFaction)score+=Math.max(0,sim.timeLimit-sim.time)*.10;if((stats.captures||0)===0)score-=22;return+score.toFixed(3);}
function resultRecord(sim,candidateId,candidateFaction,score,scenario,trainingSeed,scenarioIndex){var stats=sim.objectiveStats||{},counts=objectiveCounts(sim);return{candidateId:candidateId,candidateFaction:candidateFaction,winner:sim.winner||'none',time:+sim.time.toFixed(2),score:score,trainingSeed:trainingSeed,scenarioSeed:scenario.seed,scenarioId:scenario.id,scenarioIndex:scenarioIndex,fingerprint:scenario.fingerprint,usAlive:units(sim,'us').length,geAlive:units(sim,'ge').length,usForceValue:+forceValue(sim,'us').toFixed(2),geForceValue:+forceValue(sim,'ge').toFixed(2),usObjectives:counts.us||0,geObjectives:counts.ge||0,captures:stats.captures||0,neutralizations:stats.neutralizations||0,capturesByFaction:stats.capturesByFaction||{},pressureSecondsByFaction:stats.pressureSecondsByFaction||{}};}
function installScenario(sim,seed,trainingSeed,index){return root.BattleTownObjectives.regenerate(sim.scene,sim.heightAt,seed,{trainingSeed:trainingSeed,scenarioIndex:index},sim);}
async function runMatch(sim,rawRestart,baseline,candidate,candidateId,candidateFaction,scenarioSeed,trainingSeed,scenarioIndex,status,matchNo,totalMatches,runOpts){
  var scenario=installScenario(sim,scenarioSeed,trainingSeed,scenarioIndex);
  root.BattleAIPolicy.setMatchPolicies(sim,candidateFaction==='us'?candidate:baseline,candidateFaction==='ge'?candidate:baseline);rawRestart();sim.manualEnded=false;sim.winner=null;sim.paused=false;sim.trainingMode=true;sim.timeScale=1;
  if(root.BattleTelemetry)root.BattleTelemetry.start(sim,'training',{candidateId:candidateId,candidateFaction:candidateFaction,match:matchNo,totalMatches:totalMatches,trainingSeed:trainingSeed,scenarioSeed:scenario.seed,scenarioId:scenario.id});telemetry(sim,'policy-match-start',{candidateId:candidateId,candidateFaction:candidateFaction,trainingSeed:trainingSeed,scenarioSeed:scenario.seed,scenarioId:scenario.id,scenarioIndex:scenarioIndex,fingerprint:scenario.fingerprint,genome:candidate});
  runOpts=runOpts||{};var fixedDt=.15,commandAccum=0,steps=0,maxSteps=Math.ceil((sim.timeLimit+3)/fixedDt),batchLimit=Math.max(1,runOpts.batchSize||12),modeLabel=runOpts.headless?'Headless training':'Visual training';reportProgress(runOpts,{phase:'running',headless:!!runOpts.headless,matchNo:matchNo,totalMatches:totalMatches,steps:steps,maxSteps:maxSteps});
  while(!sim.winner&&sim.time<sim.timeLimit+1&&steps<maxSteps){var batch=Math.min(batchLimit,maxSteps-steps);for(var i=0;i<batch&&!sim.winner;i++){fixedStep(sim,fixedDt);steps++;commandAccum+=fixedDt;while(commandAccum>=root.BattleCommanderAI.commandTick&&!sim.winner){commandAccum-=root.BattleCommanderAI.commandTick;root.BattleCommanderAI.update(sim,scenario,root.BattleCommanderAI.commandTick);}}if(status)status.textContent=modeLabel+' '+matchNo+'/'+totalMatches+' · map '+(scenarioIndex+1)+' · '+candidateId+' '+candidateFaction.toUpperCase()+' · '+Math.floor(sim.time)+'s';reportProgress(runOpts,{phase:'running',headless:!!runOpts.headless,matchNo:matchNo,totalMatches:totalMatches,steps:steps,maxSteps:maxSteps});sim.paused=true;await yieldToBrowser(!!runOpts.headless);sim.paused=false;}
  if(!sim.winner&&sim._checkWinner)sim._checkWinner();var score=scoreMatch(sim,candidateFaction),record=resultRecord(sim,candidateId,candidateFaction,score,scenario,trainingSeed,scenarioIndex);record.resourcesBeforeReset=sceneCounts(sim);telemetry(sim,'policy-match-result',record);
  if(status)status.textContent='Saving match '+matchNo+'/'+totalMatches+'…';reportProgress(runOpts,{phase:'saving',headless:!!runOpts.headless,matchNo:matchNo,totalMatches:totalMatches,steps:maxSteps,maxSteps:maxSteps});
  if(root.BattleTelemetry&&root.BattleTelemetry.checkpoint)await root.BattleTelemetry.checkpoint(sim,'training-match-complete',record);else if(root.BattleTelemetry){await root.BattleTelemetry.end(sim,'training-match-complete',record);await root.BattleTelemetry.flush(false);}
  disposeMatchResources(sim);await settleAfterCleanup();record.resourcesAfterReset=sceneCounts(sim);console.log('[TRAINING] match '+matchNo+'/'+totalMatches+' reset',record.resourcesBeforeReset,'->',record.resourcesAfterReset);return record;
}
function candidateSummary(entry,allCandidates){var results=entry.results,scores=results.map(function(r){return r.score;}),wins=0,losses=0,byScenario={};results.forEach(function(r){if(r.winner===r.candidateFaction)wins++;else if(r.winner&&r.winner!=='draw'&&r.winner!=='none')losses++;(byScenario[r.scenarioSeed]=byScenario[r.scenarioSeed]||[]).push(r.score);});var scenarioScores=Object.keys(byScenario).map(function(seed){return{seed:seed,score:+mean(byScenario[seed]).toFixed(3)};}),avg=mean(scores),sd=stdev(scenarioScores.map(function(x){return x.score;})),novelty=0;if(allCandidates&&allCandidates.length){var distances=[];for(var i=0;i<allCandidates.length;i++)if(allCandidates[i]!==entry)distances.push(root.BattleAIPolicy.distance(entry.genome,allCandidates[i].genome));novelty=mean(distances);}var selection=avg-sd*.18+novelty*14;return{id:entry.id,avgScore:+avg.toFixed(3),generalization:+Math.max(-200,avg-sd).toFixed(3),scenarioStd:+sd.toFixed(3),novelty:+novelty.toFixed(4),selectionFitness:+selection.toFixed(3),wins:wins,losses:losses,scenarioScores:scenarioScores,results:results,genome:entry.genome};}
function makeCandidates(baseline,count,strength,revision){count=Math.max(3,count||4);var out=[];for(var i=0;i<Math.min(3,count);i++)out.push({id:'g'+(revision+1)+'-m'+(i+1),genome:root.BattleAIPolicy.mutate(baseline,strength),results:[]});while(out.length<count){var a=out[(out.length-1)%out.length].genome,b=out[0].genome,cross=root.BattleAIPolicy.crossover(a,b);out.push({id:'g'+(revision+1)+'-x'+(out.length+1),genome:root.BattleAIPolicy.mutate(cross,strength*.72),results:[]});}return out;}
async function rememberScenarioExperience(best,trainingSeed,scenarioSeed,promotion){var scenarioResults=best.results.filter(function(r){return r.scenarioSeed===scenarioSeed;}),score=mean(scenarioResults.map(function(r){return r.score;}));if(!scenarioResults.length||score<=0)return null;var exemplar=scenarioResults.slice().sort(function(a,b){return b.score-a.score;})[0];return root.BattleAIPolicy.remember({seed:scenarioSeed,scenarioId:exemplar.scenarioId,trainingSeed:trainingSeed,fingerprint:exemplar.fingerprint,genome:best.genome,score:+score.toFixed(3),winner:exemplar.winner,revision:promotion&&promotion.revision||root.BattleAIPolicy.revision,candidateId:best.id,stats:{time:exemplar.time,captures:exemplar.captures,neutralizations:exemplar.neutralizations,usObjectives:exemplar.usObjectives,geObjectives:exemplar.geObjectives,usForceValue:exemplar.usForceValue,geForceValue:exemplar.geForceValue}});}
async function train(sim,opts){
  opts=opts||{};if(sim._trainingRunning)return null;sim._trainingRunning=true;var button=opts.button||null,status=opts.status||document.getElementById('aiTestStatus');if(button)button.disabled=true;var originalScenario=sim.scene.metadata&&sim.scene.metadata.battleScenario,originalSeed=originalScenario&&originalScenario.seed||root.BattleScenarioGenerator.newSeed('live');
  var rawRestart=sim._controlRawRestart||sim.restart.bind(sim),saved={onFire:sim.onFire,onShot:sim.onShot,onCallout:sim.onCallout,onUpdate:sim.onUpdate,onWinner:sim.onWinner,timeScale:sim.timeScale,paused:sim.paused};sim.onFire=function(){};sim.onShot=function(){};sim.onCallout=function(){};sim.onUpdate=function(){};sim.onWinner=function(){};
  var baseline=root.BattleAIPolicy.get(),baselineRevision=root.BattleAIPolicy.revision,headless=!!opts.headless,candidateCount=opts.candidates||4,scenarioCount=opts.scenarios||3,strength=opts.mutationStrength==null?.18:+opts.mutationStrength,trainingSeed=String(opts.seed||root.BattleScenarioGenerator.newSeed('training')),scenarioSeeds=[];for(var s=0;s<scenarioCount;s++)scenarioSeeds.push(trainingSeed+'-map-'+(s+1));var candidates=makeCandidates(baseline,candidateCount,strength,baselineRevision),totalMatches=candidateCount*scenarioCount*2,matchNo=0,promotion=null,summaries=[],runOpts={headless:headless,batchSize:opts.batchSize||(headless?120:12),onProgress:opts.onProgress},engine=sim.scene&&sim.scene.getEngine&&sim.scene.getEngine(),renderStopped=false,telemetryConsoleLogging=null;
  try{
    if(headless&&engine&&opts.renderLoop){sim.paused=true;engine.stopRenderLoop(opts.renderLoop);renderStopped=true;}
    if(root.BattleTelemetry&&root.BattleTelemetry.setConsoleLogging)telemetryConsoleLogging=root.BattleTelemetry.setConsoleLogging(false);
    if(root.BattleTelemetry){await root.BattleTelemetry.end(sim,'training-start');root.BattleTelemetry.start(sim,'training',{phase:'generation-metadata',baselineRevision:baselineRevision,totalMatches:totalMatches,trainingSeed:trainingSeed,headless:headless});}telemetry(sim,'policy-training-start',{genomeVersion:2,revision:baselineRevision,trainingSeed:trainingSeed,scenarioSeeds:scenarioSeeds,candidates:candidateCount,totalMatches:totalMatches,headless:headless,baseline:baseline});candidates.forEach(function(candidate){telemetry(sim,'policy-candidate',{candidateId:candidate.id,genome:candidate.genome,distanceFromBaseline:root.BattleAIPolicy.distance(candidate.genome,baseline),ruleCount:candidate.genome.rules.length,doctrine:candidate.genome.doctrine});});if(root.BattleTelemetry)await root.BattleTelemetry.checkpoint(sim,'training-metadata-complete');
    for(var i=0;i<candidates.length;i++){var candidate=candidates[i];for(var si=0;si<scenarioSeeds.length;si++)for(var sideIndex=0;sideIndex<2;sideIndex++){var side=sideIndex===0?'us':'ge';matchNo++;candidate.results.push(await runMatch(sim,rawRestart,baseline,candidate.genome,candidate.id,side,scenarioSeeds[si],trainingSeed,si,status,matchNo,totalMatches,runOpts));}}
    summaries=candidates.map(function(c){return candidateSummary(c,candidates);});summaries.sort(function(a,b){return b.selectionFitness-a.selectionFitness;});var best=summaries[0],threshold=opts.promotionThreshold==null?8:+opts.promotionThreshold,shouldPromote=!!(best&&best.avgScore>0&&best.selectionFitness>=threshold&&best.wins>=best.losses&&best.generalization>-55);
    var trainingSummary={genomeVersion:2,trainingSeed:trainingSeed,baselineRevision:baselineRevision,scenarioSeeds:scenarioSeeds,totalMatches:totalMatches,headless:headless,promotionThreshold:threshold,best:best?{id:best.id,avgScore:best.avgScore,selectionFitness:best.selectionFitness,generalization:best.generalization,scenarioStd:best.scenarioStd,novelty:best.novelty,wins:best.wins,losses:best.losses,ruleCount:best.genome.rules.length,doctrine:best.genome.doctrine,scenarioScores:best.scenarioScores}:null,candidates:summaries.map(function(x){return{id:x.id,avgScore:x.avgScore,selectionFitness:x.selectionFitness,generalization:x.generalization,novelty:x.novelty,wins:x.wins,losses:x.losses,ruleCount:x.genome.rules.length};}),promoted:shouldPromote};
    if(root.BattleTelemetry)root.BattleTelemetry.start(sim,'training',{phase:'generation-summary',baselineRevision:baselineRevision,trainingSeed:trainingSeed});telemetry(sim,'policy-training-summary',trainingSummary);if(shouldPromote){promotion=await root.BattleAIPolicy.persist(best.genome,{score:best.selectionFitness,matches:best.results.length,baselineScore:0,candidateId:best.id,generation:baselineRevision+1,sourceBuild:root.BATTLE_BUILD||'dev',trainingSeed:trainingSeed,scenarioCount:scenarioCount,validationScore:best.generalization,noveltyScore:best.novelty});telemetry(sim,'policy-promoted',{candidateId:best.id,revision:promotion.revision,score:best.selectionFitness,avgScore:best.avgScore,generalization:best.generalization,trainingSeed:trainingSeed,genome:best.genome});}
    for(var rs=0;rs<scenarioSeeds.length;rs++)await rememberScenarioExperience(best,trainingSeed,scenarioSeeds[rs],promotion);if(root.BattleTelemetry)await root.BattleTelemetry.checkpoint(sim,'training-generation-complete',{promoted:!!promotion,revision:root.BattleAIPolicy.revision,trainingSeed:trainingSeed});if(status)status.textContent=promotion?('Genome v2 learned r'+promotion.revision+' · '+best.id+' · fit '+best.selectionFitness+' · gen '+best.generalization):('Genome v2 kept r'+root.BattleAIPolicy.revision+' · best fit '+(best?best.selectionFitness:'n/a')+' · gen '+(best?best.generalization:'n/a'));reportProgress(runOpts,{phase:'complete',headless:headless,matchNo:totalMatches,totalMatches:totalMatches,steps:1,maxSteps:1});console.log('[TRAINING] Genome v2 summary',trainingSummary,promotion||'no promotion');return{summary:trainingSummary,promotion:promotion,candidates:summaries};
  }finally{root.BattleAIPolicy.clearMatchPolicies(sim);disposeMatchResources(sim);root.BattleTownObjectives.regenerate(sim.scene,sim.heightAt,originalSeed,{restoredAfterTraining:true},sim);rawRestart();sim.trainingMode=false;sim.timeScale=saved.timeScale;sim.onFire=saved.onFire;sim.onShot=saved.onShot;sim.onCallout=saved.onCallout;sim.onUpdate=saved.onUpdate;sim.onWinner=saved.onWinner;sim.paused=saved.paused;if(renderStopped&&engine&&opts.renderLoop)engine.runRenderLoop(opts.renderLoop);if(telemetryConsoleLogging!==null&&root.BattleTelemetry&&root.BattleTelemetry.setConsoleLogging)root.BattleTelemetry.setConsoleLogging(telemetryConsoleLogging);if(root.BattleTelemetry)root.BattleTelemetry.start(sim,'live',{afterTraining:true,policyRevision:root.BattleAIPolicy.revision,trainingSeed:trainingSeed,scenarioSeed:originalSeed});sim._trainingRunning=false;if(button)button.disabled=false;}
}
root.BattleAITrainer={train:train,scoreMatch:scoreMatch};console.log('[TRAINING] Genome v2 checkpoint/reset trainer v20 loaded');
})(typeof window!=='undefined'?window:globalThis);
