#!/usr/bin/env python3
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'battle/modules/16-squad-plan-stability.js'
s=p.read_text()
old="function updatePlan(sim,sq){\n  var p=sq._engagementPlan,phase=String(sq.commandPhase||'');if(sq.state==='retreat'||phase==='retreat'){closePlan(sim,sq,'retreat');return;}\n  if(p){\n    if(sq.inContact){if(p.status!=='active'&&p.activatedAt==null)p.activatedAt=sim.time;p.status='active';p.lastContactAt=sim.time;p.quietSince=null;sq._regroupBypassUntil=Math.max(+sq._regroupBypassUntil||0,sim.time+1.25);}\n    else if(p.status==='active'||p.status==='quiet'){if(p.quietSince==null)p.quietSince=sim.time;p.status='quiet';if(sim.time-p.quietSince>=QUIET_CLOSE){closePlan(sim,sq,'contact clear');p=null;}else sq._regroupBypassUntil=Math.max(+sq._regroupBypassUntil||0,sim.time+1.25);}\n    if(p&&p.status==='staged'&&signature(sq)!==p.signature){closePlan(sim,sq,'intent replaced');p=null;}\n    if(p&&p.status==='staged'&&sim.time>=p.until){closePlan(sim,sq,'lease expired');p=null;}\n  }\n  if(!sq._engagementPlan&&TACTICAL[phase]&&!EMERGENCY[phase])stagePlan(sim,sq);else if(sq._engagementPlan){sq._stablePlan=sq._engagementPlan;syncTasks(sq,sq._engagementPlan);}\n}"
new="function updatePlan(sim,sq){\n  var p=sq._engagementPlan,phase=String(sq.commandPhase||''),sig=signature(sq);if(sq.state==='retreat'||phase==='retreat'){closePlan(sim,sq,'retreat');sq._planDormantSignature=null;return;}\n  if(sq._planDormantSignature&&sq._planDormantSignature!==sig)sq._planDormantSignature=null;\n  if(p){\n    if(sq.inContact){sq._planDormantSignature=null;if(p.status!=='active'&&p.activatedAt==null)p.activatedAt=sim.time;p.status='active';p.lastContactAt=sim.time;p.quietSince=null;sq._regroupBypassUntil=Math.max(+sq._regroupBypassUntil||0,sim.time+1.25);}\n    else if(p.status==='active'||p.status==='quiet'){if(p.quietSince==null)p.quietSince=sim.time;p.status='quiet';if(sim.time-p.quietSince>=QUIET_CLOSE){sq._planDormantSignature=p.signature;closePlan(sim,sq,'contact clear');p=null;}else sq._regroupBypassUntil=Math.max(+sq._regroupBypassUntil||0,sim.time+1.25);}\n    if(p&&p.status==='staged'&&sig!==p.signature){closePlan(sim,sq,'intent replaced');p=null;}\n    if(p&&p.status==='staged'&&sim.time>=p.until){closePlan(sim,sq,'lease expired');p=null;}\n  }\n  /* A plan that just closed because the battlefield went quiet stays dormant until either contact\n     returns or the commander materially changes intent. Do not close and immediately recreate the\n     same plan with a new serial; that only churns positional tasks. */\n  if(!sq._engagementPlan&&TACTICAL[phase]&&!EMERGENCY[phase]&&(sq.inContact||sq._planDormantSignature!==sig))stagePlan(sim,sq);else if(sq._engagementPlan){sq._stablePlan=sq._engagementPlan;syncTasks(sq,sq._engagementPlan);}\n}"
if old not in s: raise SystemExit('updatePlan block not found')
s=s.replace(old,new)
s=s.replace("q._engagementPlanSerial=0;q._commandLeaseAwaitingEvaluation=false;","q._engagementPlanSerial=0;q._planDormantSignature=null;q._commandLeaseAwaitingEvaluation=false;")
p.write_text(s)
Path(__file__).unlink()
